In [1]:
import os
print(os.getcwd())

C:\Users\koush\Desktop\crud-sla-anomaly-detection\notebooks

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/synthetic_ecomop_logs_1.csv")

In [3]:
import numpy as np

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["hour"] = df["timestamp"].dt.hour

# cyclical encoding (VERY IMPORTANT)
df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24)

In [4]:
df = pd.get_dummies(df, columns=["operation"])

In [5]:
df.head()

,timestamp,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_add_to_cart,operation_browse_products,operation_checkout,operation_payment,operation_view_cart
0,2025-01-01,121586,21.479,617,5.404,0,0.0,1.0,False,True,False,False,False
1,2025-01-01,26345,30.134,436,10.757,0,0.0,1.0,False,False,False,False,True
2,2025-01-01,24172,47.051,585,31.103,0,0.0,1.0,True,False,False,False,False
3,2025-01-01,8301,179.964,275,107.498,0,0.0,1.0,False,False,True,False,False
4,2025-01-01,6288,203.375,294,174.204,0,0.0,1.0,False,False,False,True,False

In [6]:
df["total_vol"] = df["success_vol"] + df["fail_vol"]

df["fail_ratio"] = df["fail_vol"] / (df["total_vol"] + 1)

df["latency_gap"] = df["success_rt_avg"] - df["fail_rt_avg"]

df["vol_per_latency"] = df["total_vol"] / (df["success_rt_avg"] + 1)

In [7]:
df.head()

,timestamp,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_add_to_cart,operation_browse_products,operation_checkout,operation_payment,operation_view_cart,total_vol,fail_ratio,latency_gap,vol_per_latency
0,2025-01-01,121586,21.479,617,5.404,0,0.0,1.0,False,True,False,False,False,122203,0.005049,16.075,5436.318342
1,2025-01-01,26345,30.134,436,10.757,0,0.0,1.0,False,False,False,False,True,26781,0.016280,19.377,860.185007
2,2025-01-01,24172,47.051,585,31.103,0,0.0,1.0,True,False,False,False,False,24757,0.023629,15.948,515.223408
3,2025-01-01,8301,179.964,275,107.498,0,0.0,1.0,False,False,True,False,False,8576,0.032062,72.466,47.390641
4,2025-01-01,6288,203.375,294,174.204,0,0.0,1.0,False,False,False,True,False,6582,0.044660,29.171,32.205505

In [8]:
df = df.dropna()
df = df.drop(columns=["timestamp"])
df.head()

,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_add_to_cart,operation_browse_products,operation_checkout,operation_payment,operation_view_cart,total_vol,fail_ratio,latency_gap,vol_per_latency
0,121586,21.479,617,5.404,0,0.0,1.0,False,True,False,False,False,122203,0.005049,16.075,5436.318342
1,26345,30.134,436,10.757,0,0.0,1.0,False,False,False,False,True,26781,0.016280,19.377,860.185007
2,24172,47.051,585,31.103,0,0.0,1.0,True,False,False,False,False,24757,0.023629,15.948,515.223408
3,8301,179.964,275,107.498,0,0.0,1.0,False,False,True,False,False,8576,0.032062,72.466,47.390641
4,6288,203.375,294,174.204,0,0.0,1.0,False,False,False,True,False,6582,0.044660,29.171,32.205505

In [9]:
df.to_csv("../data/processed/features_ecomop_logs_1.csv", index=False)

In [10]:
df.head(5)

,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_add_to_cart,operation_browse_products,operation_checkout,operation_payment,operation_view_cart,total_vol,fail_ratio,latency_gap,vol_per_latency
0,121586,21.479,617,5.404,0,0.0,1.0,False,True,False,False,False,122203,0.005049,16.075,5436.318342
1,26345,30.134,436,10.757,0,0.0,1.0,False,False,False,False,True,26781,0.016280,19.377,860.185007
2,24172,47.051,585,31.103,0,0.0,1.0,True,False,False,False,False,24757,0.023629,15.948,515.223408
3,8301,179.964,275,107.498,0,0.0,1.0,False,False,True,False,False,8576,0.032062,72.466,47.390641
4,6288,203.375,294,174.204,0,0.0,1.0,False,False,False,True,False,6582,0.044660,29.171,32.205505