In [1]:
import os
print(os.getcwd())

C:\Users\koush\Desktop\crud-sla-anomaly-detection\notebooks

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/synthetic_crudop_logs.csv")

In [3]:
import numpy as np

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["hour"] = df["timestamp"].dt.hour

# cyclical encoding (VERY IMPORTANT)
df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24)

In [4]:
df = pd.get_dummies(df, columns=["operation"])

In [5]:
df.head()

,timestamp,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_DELETE,operation_GET,operation_POST,operation_PUT
0,2025-01-01 00:00:00,78996,12.441,418,2.383,0,0.000000,1.000000,False,True,False,False
1,2025-01-01 00:00:00,9558,32.689,1554,10.685,0,0.000000,1.000000,False,False,True,False
2,2025-01-01 00:00:00,15498,34.332,2913,19.612,0,0.000000,1.000000,False,False,False,True
3,2025-01-01 00:00:00,6952,23.306,1762,12.749,0,0.000000,1.000000,True,False,False,False
4,2025-01-01 01:00:00,79648,7.007,411,3.606,1,0.258819,0.965926,False,True,False,False

In [6]:
df["total_vol"] = df["success_vol"] + df["fail_vol"]

df["fail_ratio"] = df["fail_vol"] / (df["total_vol"] + 1)

df["latency_gap"] = df["success_rt_avg"] - df["fail_rt_avg"]

df["vol_per_latency"] = df["total_vol"] / (df["success_rt_avg"] + 1)

In [7]:
df.head()

,timestamp,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_DELETE,operation_GET,operation_POST,operation_PUT,total_vol,fail_ratio,latency_gap,vol_per_latency
0,2025-01-01 00:00:00,78996,12.441,418,2.383,0,0.000000,1.000000,False,True,False,False,79414,0.005263,10.058,5908.340153
1,2025-01-01 00:00:00,9558,32.689,1554,10.685,0,0.000000,1.000000,False,False,True,False,11112,0.139836,22.004,329.840601
2,2025-01-01 00:00:00,15498,34.332,2913,19.612,0,0.000000,1.000000,False,False,False,True,18411,0.158212,14.720,521.085701
3,2025-01-01 00:00:00,6952,23.306,1762,12.749,0,0.000000,1.000000,True,False,False,False,8714,0.202180,10.557,358.512301
4,2025-01-01 01:00:00,79648,7.007,411,3.606,1,0.258819,0.965926,False,True,False,False,80059,0.005134,3.401,9998.626202

In [8]:
df = df.dropna()
df = df.drop(columns=["timestamp"])
df.head()

,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_DELETE,operation_GET,operation_POST,operation_PUT,total_vol,fail_ratio,latency_gap,vol_per_latency
0,78996,12.441,418,2.383,0,0.000000,1.000000,False,True,False,False,79414,0.005263,10.058,5908.340153
1,9558,32.689,1554,10.685,0,0.000000,1.000000,False,False,True,False,11112,0.139836,22.004,329.840601
2,15498,34.332,2913,19.612,0,0.000000,1.000000,False,False,False,True,18411,0.158212,14.720,521.085701
3,6952,23.306,1762,12.749,0,0.000000,1.000000,True,False,False,False,8714,0.202180,10.557,358.512301
4,79648,7.007,411,3.606,1,0.258819,0.965926,False,True,False,False,80059,0.005134,3.401,9998.626202

In [9]:
df.to_csv("../data/processed/features_crudop_logs.csv", index=False)

In [11]:
df.head(5)

,success_vol,success_rt_avg,fail_vol,fail_rt_avg,hour,hour_sin,hour_cos,operation_DELETE,operation_GET,operation_POST,operation_PUT,total_vol,fail_ratio,latency_gap,vol_per_latency
0,78996,12.441,418,2.383,0,0.000000,1.000000,False,True,False,False,79414,0.005263,10.058,5908.340153
1,9558,32.689,1554,10.685,0,0.000000,1.000000,False,False,True,False,11112,0.139836,22.004,329.840601
2,15498,34.332,2913,19.612,0,0.000000,1.000000,False,False,False,True,18411,0.158212,14.720,521.085701
3,6952,23.306,1762,12.749,0,0.000000,1.000000,True,False,False,False,8714,0.202180,10.557,358.512301
4,79648,7.007,411,3.606,1,0.258819,0.965926,False,True,False,False,80059,0.005134,3.401,9998.626202